### ISSUE TITLE
bblfsh spawns zombie processes when it runs on ubuntu

### ISSUE THREAD

**Issue by zurk** [bblfsh/server#78] opened 2017-07-20 16:14 UTC
### What happened?
I worked with bblfsh on science-3 machine and found that too many zombies spawn in the system.
when I close bblfsh container they are gone away.

### How can you reproduce it?
I work with bblfsh on science-3 machine.
It will be easier to reproduce it on it (In case, I can show you how) but in general, I do something like this:
run bblfsh in the usual way
`docker run --privileged -p 9432:9432 --name bblfsh bblfsh/server`

run another container in my case it is 
`docker run --rm -it -v /storage:/storage --device /dev/nvidiactl --device /dev/nvidia-uvm -v /data:/data -expose=9432 --privileged -e "LD_PRELOAD=" srcd/science bash`

May be it is reproducible just in the system.

then
```
pip3 install git+https://github.com/bblfsh/client-python
pip3 install git+https://github.com/src-d/ast2vec@develop
```
and then run attached script. 
[entry_point.py.zip](https://github.com/bblfsh/server/files/1162960/entry_point.py.zip)

You can check kind of zombies number with `ps aux | grep Z | wc -l` before and after.
In my case it 4 and 15.

### Priority:
Medium

I need to get UAST for many repos in nearest future, so it quite important.

### _Other info you may need_:
I tried to reproduce the same result under MacOS and failed

**Comment by abeaumont** [comment] 2017-07-20 16:29
I'd say it's a duplicate of #42

**Comment by zurk** [comment] 2017-07-21 08:18
Seems to be.
Can you estimate when it will be fixed?

**Comment by abeaumont** [comment] 2017-07-21 08:22
@zurk I'll close this, let's move the discussion to #42 to avoid duplication

**Closed by abeaumont** 2017-07-21 08:22 UTC

**Comment by juanjux** [comment] 2017-07-26 06:46
Should be fixed by https://github.com/bblfsh/server/pull/79. I've also tested with the provided script and no zombie processes were created. Please note that the script doesn't work anymore with the current `develop` branch of `ast2vec`.
