### ISSUE TITLE
Add the ability to query for the server's version

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/server#86] opened 2017-08-17 08:57 UTC
ML team needs to have an API to ask the running server for its version.

Discussions:
https://src-d.slack.com/archives/C4NNGEVGW/p1497445078106377
https://src-d.slack.com/archives/C4NNGEVGW/p1502888509000205

Related to #28

**Comment by zurk** [comment] 2017-08-17 09:12
Also, want to clarify that it is not only on the server but language drivers. It always confusing when you rerun your code after the update.
Another use case when you try to understand is my dataset outdated and some important updates were introduced or it is not so critical for that moment.

**Comment by abeaumont** [comment] 2017-08-17 09:13
so this is a duplicate of #28?

**Comment by zurk** [comment] 2017-08-17 09:15
Oh, no. :) 
this is for the server,
#28 about drivers.

I missed it.

**Comment by abeaumont** [comment] 2017-08-17 09:18
Why do you need the server version to be published through an API?

**Comment by zurk** [comment] 2017-08-17 09:42
For me is the same reason. I can understand that my dataset is outdated. Some repositories or files processing may fail because of bblfsh server for example. 

I think @vmarkovtsev also want to have something like reproducibility of experiments and datasets of course.

**Comment by abeaumont** [comment] 2017-08-17 09:51
Thanks @zurk! I understand why knowing the server version is important, I'm asking why you need it specifically exported in the API instead or just having, say, `bblfsh server --version` or any other way.

**Comment by zurk** [comment] 2017-08-17 09:55
Oh, I think just to have the straightforward way to specify it in our datasets. 
But it is my guess, I leave it for @vmarkovtsev. :)

**Comment by marnovo** [comment] 2017-08-17 12:35
Nice to see the discussion flowing, this is important. Thanks guys! 👍

**Comment by vmarkovtsev** [comment] 2017-08-17 12:37
@abeaumont Because we have an abstraction and we do not control the actual docker thing.

**Comment by vmarkovtsev** [comment] 2017-08-17 12:38
Every API shall have versioning. For example, GitHub API.

**Comment by abeaumont** [comment] 2017-08-17 12:58
@vmarkovtsev We (bblfsh project) are not building a remote API, we're building a server, language drivers and various libraries and clients. Anyway, we may want to add such information for the server too, the same way as for drivers as in #28. I'll let @mcuadros decide how this is preferred.

**Comment by vmarkovtsev** [comment] 2017-08-17 13:06
ML team does consume an API. We do not want (and IMHO are not supposed to) mess up with any infrastructure, launching servers, updating the stuff, checking if Rafa did update the container yesterday, etc. Any ML experiment should be reproducible, and without using bblfsh versioning, we simply cannot achieve that. 

If there is a Kubernetes API to ask for the bblfsh container version, we are fine though, but it means that we require all our potential ML users to run bblfsh in Kubernetes (good luck on that with the ML crowd).

**Comment by vmarkovtsev** [comment] 2017-08-17 13:08
I think now we understand what is the conceptual problem here and #28

**Comment by abeaumont** [comment] 2017-08-21 15:57
https://github.com/bblfsh/server/issues/28#issuecomment-323783007 contains more information about how this will be done.

**Comment by abeaumont** [comment] 2017-08-30 14:13
Solved by #93

**Closed by abeaumont** 2017-08-30 14:13 UTC
