### ISSUE TITLE
Concurrent queries return randomly corrupted UASTs

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/server#34] opened 2017-06-16 15:45 UTC
We use the following script to reproduce the problem:

```
python3 -m bblfsh  ast2vec/ast2vec/__init__.py  ast2vec/ast2vec/__main__.py  ast2vec/ast2vec/dataset.py  ast2vec/ast2vec/df.py  ast2vec/ast2vec/enry.py  ast2vec/ast2vec/id2vec.py  ast2vec/ast2vec/id_embedding.py  ast2vec/ast2vec/repo2base.py  ast2vec/ast2vec/repo2coocc.py  ast2vec/ast2vec/repo2nbow.py  ast2vec/ast2vec/swivel.py  ast2vec/ast2vec/utils/__init__.py  ast2vec/ast2vec/utils/ast2vec.py  ast2vec/ast2vec/utils/gogo_pb2.py  ast2vec/ast2vec/utils/gogo_pb2_grpc.py  ast2vec/ast2vec/utils/sdk_protocol_pb2.py  ast2vec/ast2vec/utils/sdk_protocol_pb2_grpc.py  ast2vec/ast2vec/utils/uast_pb2.py  ast2vec/ast2vec/utils/uast_pb2_grpc.py  ast2vec/data/test.py  ast2vec/src/bblfsh/bblfsh/__init__.py  ast2vec/src/bblfsh/bblfsh/__main__.py  ast2vec/src/bblfsh/bblfsh/client.py  ast2vec/src/bblfsh/bblfsh/github/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/protocol/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/protocol/generated_pb2.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/protocol/generated_pb2_grpc.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/uast/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/uast/generated_pb2.py  ast2vec/src/bblfsh/bblfsh/github/com/gogo/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/gogo/protobuf/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/gogo/protobuf/gogoproto/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/gogo/protobuf/gogoproto/gogo_pb2.py  ast2vec/src/bblfsh/bblfsh/launcher.py  ast2vec/src/bblfsh/bblfsh/test.py  ast2vec/src/bblfsh/setup.py > 1.txt &
python3 -m bblfsh  ast2vec/ast2vec/__init__.py  ast2vec/ast2vec/__main__.py  ast2vec/ast2vec/dataset.py  ast2vec/ast2vec/df.py  ast2vec/ast2vec/enry.py  ast2vec/ast2vec/id2vec.py  ast2vec/ast2vec/id_embedding.py  ast2vec/ast2vec/repo2base.py  ast2vec/ast2vec/repo2coocc.py  ast2vec/ast2vec/repo2nbow.py  ast2vec/ast2vec/swivel.py  ast2vec/ast2vec/utils/__init__.py  ast2vec/ast2vec/utils/ast2vec.py  ast2vec/ast2vec/utils/gogo_pb2.py  ast2vec/ast2vec/utils/gogo_pb2_grpc.py  ast2vec/ast2vec/utils/sdk_protocol_pb2.py  ast2vec/ast2vec/utils/sdk_protocol_pb2_grpc.py  ast2vec/ast2vec/utils/uast_pb2.py  ast2vec/ast2vec/utils/uast_pb2_grpc.py  ast2vec/data/test.py  ast2vec/src/bblfsh/bblfsh/__init__.py  ast2vec/src/bblfsh/bblfsh/__main__.py  ast2vec/src/bblfsh/bblfsh/client.py  ast2vec/src/bblfsh/bblfsh/github/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/protocol/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/protocol/generated_pb2.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/protocol/generated_pb2_grpc.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/uast/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/uast/generated_pb2.py  ast2vec/src/bblfsh/bblfsh/github/com/gogo/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/gogo/protobuf/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/gogo/protobuf/gogoproto/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/gogo/protobuf/gogoproto/gogo_pb2.py  ast2vec/src/bblfsh/bblfsh/launcher.py  ast2vec/src/bblfsh/bblfsh/test.py  ast2vec/src/bblfsh/setup.py > 2.txt &
python3 -m bblfsh  ast2vec/ast2vec/__init__.py  ast2vec/ast2vec/__main__.py  ast2vec/ast2vec/dataset.py  ast2vec/ast2vec/df.py  ast2vec/ast2vec/enry.py  ast2vec/ast2vec/id2vec.py  ast2vec/ast2vec/id_embedding.py  ast2vec/ast2vec/repo2base.py  ast2vec/ast2vec/repo2coocc.py  ast2vec/ast2vec/repo2nbow.py  ast2vec/ast2vec/swivel.py  ast2vec/ast2vec/utils/__init__.py  ast2vec/ast2vec/utils/ast2vec.py  ast2vec/ast2vec/utils/gogo_pb2.py  ast2vec/ast2vec/utils/gogo_pb2_grpc.py  ast2vec/ast2vec/utils/sdk_protocol_pb2.py  ast2vec/ast2vec/utils/sdk_protocol_pb2_grpc.py  ast2vec/ast2vec/utils/uast_pb2.py  ast2vec/ast2vec/utils/uast_pb2_grpc.py  ast2vec/data/test.py  ast2vec/src/bblfsh/bblfsh/__init__.py  ast2vec/src/bblfsh/bblfsh/__main__.py  ast2vec/src/bblfsh/bblfsh/client.py  ast2vec/src/bblfsh/bblfsh/github/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/protocol/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/protocol/generated_pb2.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/protocol/generated_pb2_grpc.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/uast/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/uast/generated_pb2.py  ast2vec/src/bblfsh/bblfsh/github/com/gogo/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/gogo/protobuf/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/gogo/protobuf/gogoproto/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/gogo/protobuf/gogoproto/gogo_pb2.py  ast2vec/src/bblfsh/bblfsh/launcher.py  ast2vec/src/bblfsh/bblfsh/test.py  ast2vec/src/bblfsh/setup.py > 3.txt
```

Please note that you need the patch to client-python: https://github.com/vmarkovtsev/bblfsh.client-python/tree/main-change

Result: 1.txt, 2.txt and 3.txt are randomly different (checked with `diff`). Besides, some files are in wrong places or empty.

**Comment by vmarkovtsev** [comment] 2017-06-16 15:51
Actually, we seem to reproduce it even with a single process. If I add `time.sleep()` between requests, they become valid and 100% the same.

**Comment by vmarkovtsev** [comment] 2017-06-16 15:53
Another observation: we did not test it with a single instance of the driver. We will test it now.

**Comment by EgorBu** [comment] 2017-06-16 16:06
[log.txt.gz](https://github.com/bblfsh/server/files/1081337/log.txt.gz)

**Comment by EgorBu** [comment] 2017-06-16 16:07
This is the log we get. I see errors with empty `__init__.py`, though not sure if they are relevant. Besides, the environment var Vadim added in https://github.com/bblfsh/server/pull/25 seem to not work.

**Comment by vmarkovtsev** [comment] 2017-06-16 16:10
@juanjux BTW those errors on empty files do not look like gracefully handled :)

**Comment by abeaumont** [comment] 2017-06-16 16:10
Does it only happen with all these files or still happens with a smaller number of files? If the latter, could you provide an example with the minimum number of files and those files to try to reproduce the problem?

**Comment by abeaumont** [comment] 2017-06-16 16:11
This may or may not be related with https://github.com/bblfsh/java-driver/issues/19

**Comment by vmarkovtsev** [comment] 2017-06-16 16:13
We will try to reduce it now.

**Comment by EgorBu** [comment] 2017-06-16 16:24
We tortured it to death!

` ` ` 
status: FATAL
errors: "timedout: all drivers are busy"

status: FATAL
errors: "timedout: all drivers are busy"

status: FATAL
errors: "timedout: all drivers are busy"

status: FATAL
errors: "timedout: all drivers are busy"

status: FATAL
errors: "timedout: all drivers are busy"

status: FATAL
errors: "timedout: all drivers are busy"

status: FATAL
errors: "timedout: all drivers are busy"

status: FATAL
errors: "timedout: all drivers are busy"

status: FATAL
errors: "timedout: all drivers are busy"

status: FATAL
errors: "timedout: all drivers are busy"

status: FATAL
errors: "timedout: all drivers are busy"

status: FATAL
errors: "timedout: all drivers are busy"

status: FATAL
errors: "timedout: all drivers are busy"

status: FATAL
errors: "timedout: all drivers are busy"

status: FATAL
errors: "timedout: all drivers are busy"

status: FATAL
errors: "timedout: all drivers are busy"
` ` `

**Comment by EgorBu** [comment] 2017-06-16 16:36
This is the minimal example which reproduces the problem in 50% of the cases:

```
python3 -m bblfsh    ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/protocol/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/protocol/generated_pb2.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/protocol/generated_pb2_grpc.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/uast/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/uast/generated_pb2.py > 1.txt &
python3 -m bblfsh    ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/protocol/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/protocol/generated_pb2.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/protocol/generated_pb2_grpc.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/uast/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/uast/generated_pb2.py > 2.txt &
python3 -m bblfsh    ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/protocol/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/protocol/generated_pb2.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/protocol/generated_pb2_grpc.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/uast/__init__.py  ast2vec/src/bblfsh/bblfsh/github/com/bblfsh/sdk/uast/generated_pb2.py > 3.txt &
```

**Comment by juanjux** [comment] 2017-06-20 15:48
I'll try to reproduce and fix this tomorrow as I return from CurryOn. 

Sorry for the delay.

**Comment by juanjux** [comment] 2017-06-21 08:57
Not the same problem (but could be related), I'm seeing that parsing those __init__.py files directly from the driver (without the server) produce a fatal error "missing content" (since the files are empty) which should be a normal "error" (with an empty AST returned) and not a fatal (since fatal errors stop any further processing from that driver and this isn't really anything unrecoverable). I'll start by fixing that and checking if that fix the problem.

This could also be related with the blocking problem because we suspect the server is not closing failing drivers correctly and thus the limit of live images is reached, but that will come later.

**Comment by juanjux** [comment] 2017-06-21 15:32
Update: merged the bug related with empty files causing a fatal error but now I'm seeing an error with the buffer size. This one was recently fixed but the docker image of the server probably has an old version. I'll try with a locally compiled server.

**Comment by juanjux** [comment] 2017-06-22 08:13
Update: this bug seems to be a several-headed beast, I'll write and keep updtated a list of found problems so you can see the status from this message. Maybe later I'll split this into several different issues.

- [X] Python driver produces fatal error with empty files
- [ ] Buffer overrun error. **In progress** (shouldn't happen with the current version of the SDK and can't reproduce parsing the file directly with the driver, but for some reason still happens with the python-client even runnig a locally compiled and updated server reading driver images from the local docker daemon.)
- [ ] Sometimes the request hangs forever.
- [ ] Odd `\r found at start of the file` message that pop ups randomly.

**Comment by juanjux** [comment] 2017-06-22 11:24
Since I can't reproduce this problem anymore after the first fixes I'll close this one. I'll publish new docker images of the server and python-driver soon but meanwhile you can test with a server and python-driver build from ~master. Build the python driver first:

 ```bash
python-driver$ make build
```

then tag the created image (`docker tag`) as `bblfsh/python-driver:latest`. Then build  and run the server with: 

```bash
server$ cd cmd/bblfsh
bblfsh$ go build
bblfsh$ sudo rm -rf /tmp/bblfsh-runtime
bblfsh$ sudo ./bblfsh server --transport=docker-daemon
```
Then you can run the python-client (remember to use the `--disable-bblfsh-autorun` option to avoid spawning a new server).

BTW, the last version of the python-client seem to work a little different than the way it was explained in the report, now it has a `-f` parameter for specifying the file but if you pass it several times it only take the last file (bug?) so to reproduce this problem with that version I did a script with this content:

```bash
#!/bin/sh
python3 -m bblfsh --disable-bblfsh-autorun -l python -f sdk/__init__.py
python3 -m bblfsh --disable-bblfsh-autorun -l python -f sdk/protocol/__init__.py
python3 -m bblfsh --disable-bblfsh-autorun -l python -f sdk/protocol/generated_pb2.py
python3 -m bblfsh --disable-bblfsh-autorun -l python -f sdk/protocol/generated_pb2_grpc.py
python3 -m bblfsh --disable-bblfsh-autorun -l python -f sdk/uast/__init__.py
python3 -m bblfsh --disable-bblfsh-autorun -l python -f sdk/uast/generated_pb2.py
```

and then called it from this one:

```bash
#!/bin/sh
sh bugtest.sh > 1.txt&
sh bugtest.sh > 2.txt&
sh bugtest.sh > 3.txt&
sh bugtest.sh > 4.txt&
sh bugtest.sh > 5.txt&
```

**Comment by vmarkovtsev** [comment] 2017-06-22 11:27
@juanjux from the first message
> Please note that you need the patch to client-python: https://github.com/vmarkovtsev/bblfsh.client-python/tree/main-change

**Comment by vmarkovtsev** [comment] 2017-06-22 11:29
@juanjux The bug is not reproduced the way your script works. We knew that, that's why we created the patch. Please reopen this and let us test your fixes instead of opening the second issue about the same problems.

**Comment by juanjux** [comment] 2017-06-22 12:28
Reopened. I saw your comment but failed to notice it was a specific branch. Anyway I'm testing now with the right branch and the same script (plus the --disable-bblfsh-autorun parameter to use my local updated server) and I'm always getting the same result. Right now I'm writing a script to do it some hundreds times before I go to lunch to be 100% safe. 

Sorry for closing the bug report before your test, it's pretty common on github to do it as soon as the developer considers the bug fixed and reopening if the user says its not, but I certainly didn't saw anything on that respect on our git workflow document so I could have acted dumbed down by the happy feeling of closing this f*cking bug that I've been battling for a day and a half :)

**Comment by juanjux** [comment] 2017-06-22 12:40
This will be running in the background for a while (run with full `bash`, not `sh`). For the moment it didn't detect any changes on 60 iterations. I'm also helping Egor test the fix via Slack.

```bash
#!/bin/bash
for i in `seq 1 500`;
do
    python3 -m bblfsh --disable-bblfsh-autorun bblfsh/github/com/bblfsh/sdk/__init__.py  bblfsh/github/com/bblfsh/sdk/protocol/__init__.py  bblfsh/github/com/bblfsh/sdk/protocol/generated_pb2.py  bblfsh/github/com/bblfsh/sdk/protocol/generated_pb2_grpc.py  bblfsh/github/com/bblfsh/sdk/uast/__init__.py  bblfsh/github/com/bblfsh/sdk/uast/generated_pb2.py > 1.txt &
    python3 -m bblfsh --disable-bblfsh-autorun bblfsh/github/com/bblfsh/sdk/__init__.py  bblfsh/github/com/bblfsh/sdk/protocol/__init__.py  bblfsh/github/com/bblfsh/sdk/protocol/generated_pb2.py  bblfsh/github/com/bblfsh/sdk/protocol/generated_pb2_grpc.py  bblfsh/github/com/bblfsh/sdk/uast/__init__.py  bblfsh/github/com/bblfsh/sdk/uast/generated_pb2.py > 2.txt &
    python3 -m bblfsh --disable-bblfsh-autorun bblfsh/github/com/bblfsh/sdk/__init__.py  bblfsh/github/com/bblfsh/sdk/protocol/__init__.py  bblfsh/github/com/bblfsh/sdk/protocol/generated_pb2.py  bblfsh/github/com/bblfsh/sdk/protocol/generated_pb2_grpc.py  bblfsh/github/com/bblfsh/sdk/uast/__init__.py  bblfsh/github/com/bblfsh/sdk/uast/generated_pb2.py > 3.txt &
    sleep 5
    diff 1.txt 2.txt > /dev/null
    D1=$?
    diff 2.txt 3.txt > /dev/null
    D2=$?
    if [ "$D1" == 1 ] || [ "$D2" == 1 ]; then
        echo "Different files"
        exit 1
    fi
    rm 1.txt 2.txt 3.txt
    echo "Finished iteration $i"
done
```

**Comment by juanjux** [comment] 2017-06-22 14:27
Worked 500 times. I'll make a Docker image so Egor can test this without much hassle.

**Comment by vmarkovtsev** [comment] 2017-06-22 20:54
Thanks! Tomorrow ML has OSF, so Egor will be able to test on Monday.

**Comment by juanjux** [comment] 2017-06-23 05:45
Ok Vadim, as I spoke with Egor, I'll prepare a Dockerfile that downloads and compiles all components in ~master so this and other bugfixes are easier to test by you both before releasing new versions of the docker images on dockerhub with the bugfixes.

**Comment by juanjux** [comment] 2017-06-27 13:52
I created a project with a Dockerfile and  a test script here: https://github.com/juanjux/bblfsh-dev-image

For testing:

```
git clone https://github.com/juanjux/bblfsh-dev-image.git
cd bblfsh-dev-image
docker build -t bblfshdev .
# wait for the image to build...
docker run -v $(pwd):/script --privileged -it --rm bblfshdev bash -l /script/test_server_issue34.sh
# wait for the 500 iterations (* 5 seconds) of the test finish. make whatever other tests you need
```

**Comment by bzz** [comment] 2017-06-27 14:40
Thank you @juanjux!

**Comment by juanjux** [comment] 2017-06-28 06:50
Found the same problem tonight actually, should be fixed on the current version of the docker image project.

**Comment by bzz** [comment] 2017-06-28 09:39
🚀 Works like a charm now - both, python and java driver were built.
Thank you for prompt fixes!

**Comment by juanjux** [comment] 2017-06-28 11:32
@bzz yep, most of the complications in the Dockerfile is because of dependencies (and dependencies of dependencies) that are missing in Ubuntu 16.04, in 16.10+ is much simpler.

**Comment by smola** [comment] 2017-06-28 14:31
Feel free to reopen if it's not fixed.

**Closed by smola** 2017-06-28 14:31 UTC
Labels: bug

**Comment by vmarkovtsev** [comment] 2017-06-28 14:55
@EgorBu I don't see your test report here. Is everything's fixed for us?

**Comment by EgorBu** [comment] 2017-06-28 15:14
Not everything is well.

During the first iteration, it returns constantly the wrong result:
**4.0K instead of 3.3M**

I think it may be related to https://github.com/bblfsh/server/issues/37

```
Testing for 10 iterations with a sleep of 5 seconds
4.0K 1.txt 4.0K 2.txt 4.0K 3.txt 8.0K requirements.txt 
Finished iteration 1
3.3M 1.txt 3.3M 2.txt 3.3M 3.txt 8.0K requirements.txt
uast { internal_type: "Module" start_position { line: 1 col: 1 } roles: OP_BOOLEAN_AND } uast {
Finished iteration 2
3.3M 1.txt 3.3M 2.txt 3.3M 3.txt 8.0K requirements.txt
uast { internal_type: "Module" start_position { line: 1 col: 1 } roles: OP_BOOLEAN_AND } uast {
Finished iteration 3
3.3M 1.txt 3.3M 2.txt 3.3M 3.txt 8.0K requirements.txt
uast { internal_type: "Module" start_position { line: 1 col: 1 } roles: OP_BOOLEAN_AND } uast {
Finished iteration 4
3.3M 1.txt 3.3M 2.txt 3.3M 3.txt 8.0K requirements.txt
uast { internal_type: "Module" start_position { line: 1 col: 1 } roles: OP_BOOLEAN_AND } uast {
Finished iteration 5
3.3M 1.txt 3.3M 2.txt 3.3M 3.txt 8.0K requirements.txt
uast { internal_type: "Module" start_position { line: 1 col: 1 } roles: OP_BOOLEAN_AND } uast {
Finished iteration 6
3.3M 1.txt 3.3M 2.txt 3.3M 3.txt 8.0K requirements.txt
uast { internal_type: "Module" start_position { line: 1 col: 1 } roles: OP_BOOLEAN_AND } uast {
Finished iteration 7
3.3M 1.txt 3.3M 2.txt 3.3M 3.txt 8.0K requirements.txt
uast { internal_type: "Module" start_position { line: 1 col: 1 } roles: OP_BOOLEAN_AND } uast {
Finished iteration 8
3.3M 1.txt 3.3M 2.txt 3.3M 3.txt 8.0K requirements.txt
uast { internal_type: "Module" start_position { line: 1 col: 1 } roles: OP_BOOLEAN_AND } uast {
Finished iteration 9
3.3M 1.txt 3.3M 2.txt 3.3M 3.txt 8.0K requirements.txt
uast { internal_type: "Module" start_position { line: 1 col: 1 } roles: OP_BOOLEAN_AND } uast {
Finished iteration 10
```

**Comment by juanjux** [comment] 2017-06-28 15:41
@egor as I was telling you in slack, is a false positive because of the 5 seconds sleep is not enough for the driver instantiation, so the 3 files are still empty. Changing it to 20 seconds eliminates the problem.
