### ISSUE TITLE
High load concurrent queries hang

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/server#36] opened 2017-06-19 15:20 UTC
When I execute many (3000) concurrent queries (4 threads), Babelfish server either hangs or drops some requests without answering them. CPU load is 0%. After that, server becomes completely unresponsive and I have to restart it.

**Comment by abeaumont** [comment] 2017-06-21 13:10
@vmarkovtsev Can you explain which command you use to reproduce the bug?

**Comment by juanjux** [comment] 2017-06-22 10:04
I've found some instances of the python-client hanging randomly on my debugging of #34. It seems to happen more frequently after the previous request failed for any reason and @smola and I suspect the driver containers could not be closing correctly after some errors, which could cause all the provisioned containers to be in a non-responsive state at the end.

I'll look into it as part of that bug but maybe the fix could be the same for this one. I will post an update when I've more information.

**Comment by juanjux** [comment] 2017-06-22 12:51
I'll be fixing github.com/bblfsh/python-driver/issues/27 first since it could also be related (the problem seem to be worsened by driver failures).

**Comment by juanjux** [comment] 2017-06-28 10:37
Update: now that I've the docker to test in a controlled environment I'm seeing different behaviours on different tests:

 - I can bang the server as much as I want in paralell (even to the point of killing my machine swapping) with a Python file that produces quickly a parse error and the server never fails in this way. I think the fix to #34 helped with this.

- ...but if I send a request that produces the buffer size error from the SDK (it must be a really huge one now that the buffer size is 4MB) after the first request the server doesn't reply anymore. I'm investigating this.

**Comment by juanjux** [comment] 2017-06-30 17:15
Update: 

This bug have shown some existing problems that need to be fixed. 

Currently there is a problem that show with some files that produce an error in the Go part of the driver (the SDK) where an error is correctly returned but the next request after that one hangs. That's because the driver reads from the driver container stdin but doesn't write anything to stdout, so the server to driver communication hangs (and thus also the client to server one) . 

This doesn't mean that the server hangs; other connections to it while the first one is waiting will work since the server will instantiate more containers to manage these new connections.

- [X] Modify the encoding and decoding logic in the SDK so request to hanged drivers can timeout.
- [X] When a request timeouts trying to read or write from a driver container, log the problem and kill it.
- [ ] Detect why a driver hangs on the second request after my torture file (even while the error is correctly returned on the first one) and fix it.

**Comment by juanjux** [comment] 2017-07-01 00:04
Fixed the cause of all tests I have that resulted in container hangs: github.com/bblfsh/sdk/pull/135

We'll test together on monday and see if we can close it.

The timeout and the container killing will be done in a separate PR since I want to check some things with my team.

**Comment by juanjux** [comment] 2017-07-01 00:25
PS: @bzz

**Comment by juanjux** [comment] 2017-07-05 14:21
@EgorBu and I just checked that this (already merged) fix and the previous ones make the previous problems unreproducible. We banged the server hard with three processes sending it all the tensorflow `.py` files, repeated 20 times, and the files are always the same and the server didn't hang.

I'll release new docker images of the server and the Python & Java drivers today or tomorrow with all these fixes incorporated. Closing the issue, if the new docker images doesn't work we'll reopen it.

**Closed by juanjux** 2017-07-05 14:21 UTC
Labels: bug

**Comment by EgorBu** [comment] 2017-07-05 14:32
here it's code that we used to test
1) repository that gives different uasts for different tries: https://github.com/tensorflow/tensorflow
because of JSON decoder buffer size  - if it exceeds the limit than the driver is broken and returns errors for future requests -> so it make uasts generation not reproducible. @juanjo told that it’s related to :
https://github.com/bblfsh/sdk/pull/135
https://github.com/bblfsh/sdk/issues/130
https://github.com/bblfsh/python-driver/pull/26
and should be published in new docker image (today?)
2) code to reproduce:
```# download scripts https://src-d.slack.com/files/juanjo/F643SQ5MG/test_34_36_tensorflow.sh
git clone https://github.com/tensorflow/tensorflow
cd tensorflow
# it may take a lot of time
bash ../test_34_36_tensorflow.sh
# if it's broken - here it's python script to find the first difference in files
# https://src-d.slack.com/files/juanjo/F63GUNSSD/finddiff.py
python finddiff.py
# don't forget to delete tmp files with uasts```

**Comment by juanjux** [comment] 2017-07-06 06:28
New Python, Java and Server docker images have been released with all the latest fixes.
